*** Variables ***
${create_carrier_company_button_locator}    xpath=//a[contains(@href,"/shipment-gui/create-carrier/index")]
${create_delivery_method_button_locator}    xpath=//a[contains(@href,"/shipment-gui/create-shipment-method")]
${shipment_carrier_name_input_field_locator}    id=shipment_carrier_name
${delivery_method_key_locator}    id=shipment_method_shipmentMethodKey
${shipment_method_name_locator}    id=shipment_method_name
${carrier_dropdown_locator}    id=shipment_method_fkShipmentCarrier
${de_locator}    xpath=//input[@type='checkbox']/../../label[contains(text(),'DE')]//input
${at_locator}    xpath=//input[@type='checkbox']/../../label[contains(text(),'AT')]//input
${is_active_chekbox_locator}    id=shipment_method_isActive
${gross_price_de_chf}    id=shipment_method_prices_0_gross_amount
${gross_price_de_euro}    id=shipment_method_prices_1_gross_amount
${gross_price_at_chf}    id=shipment_method_prices_2_gross_amount
${gross_price_at_euro}    id=shipment_method_prices_3_gross_amount
${net_price_de_chf}    id=shipment_method_prices_0_net_amount
${net_price_de_euro}    id=shipment_method_prices_1_net_amount
${net_price_at_chf}    id=shipment_method_prices_2_net_amount
${net_price_at_euro}    id=shipment_method_prices_3_net_amount
${tax_set_locator}    id=shipment_method_fkTaxSet
${confirm_delete_shipment_method_button_locator}    id=shipment_method_delete_form_submit
${availability_plugin_dropdown_locator}    id=shipment_method_availabilityPlugin
${price_plugin_dropdown_locator}    id=shipment_method_pricePlugin
${delivery_time_plugin}    id=shipment_method_deliveryTimePlugin