*** Variables ***
${agent_assist_overview_link}    xpath=//div[@data-qa='component agent-control-item']//a[contains(@href,'agent/overview')]
${agent_assist_menu_overview}    xpath=//*[contains(@data-qa,'agent-navigation')]//*[contains(text(),'Overview')]
${agent_assist_menu_quote_request}    xpath=//li[@data-qa='component navigation-sidebar-item']//div[contains(text(),'Quote Requests')]
${end_customer_assistance}    xpath=//agent-control-bar//a[contains(@href,'switch_user')] | //header//*[contains(@class,'agent-control__end-session-popup')]//a[contains(@href,'_switch_user=_exit')]
${agent_logout}    xpath=//a[contains(@href,'agent/logout')]
${agent_control_widget}    xpath=//header//agent-control[@data-qa='component agent-control']
${agent_chip_trigger}    xpath=//header//agent-control[@data-qa='component agent-control']//button[contains(@class,'agent-control__chip')]
${agent_end_session_trigger}    xpath=//header//agent-control[@data-qa='component agent-control']//button[contains(@class,'js-agent-control__end-session-trigger')]
${agent_control_active_chip}    xpath=//header//agent-control[@data-qa='component agent-control']//button[contains(@class,'agent-control__chip--active')]