name: "Test CI"
on:
    pull_request:
    push:
        branches:
            - master

jobs:
  randomly-failing-job:
    runs-on: ubuntu-latest
    steps:
        - name: Generate 0 or 1
          id: generate_number
          run: echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT

        - name: Execute on master branch only
          if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master' }}
          run: echo "Hello"