name: "Test CI"

on:
    workflow_dispatch:

jobs:
    docker-alpine-php-8-2-mariadb-robot-ui:
        name: "Docker / Alpine / PHP 8.2 / MariaDB / Robot / UI"
        runs-on: ubuntu-20.04
        env:
            PROGRESS_TYPE: plain
            SPRYKER_PLATFORM_IMAGE: spryker/php:8.2
            TRAVIS: 1
            ROBOT_TESTS_ARTIFACTS_BUCKET_REGION: eu-west-1
        steps:
            - name: apt update
              run: sudo apt update