name: "[suite][master][UI][DMS-OFF]"

on:
    # schedule:
    #     -   cron: '0 1 * * 1-5'
    workflow_dispatch:

jobs:
    docker-alpine-php-8-3-mariadb-robot-ui:
        name: "Docker / Alpine / PHP 8.3 / MariaDB / Robot / UI / DMS OFF"
        runs-on: ubuntu-22.04
        env:
            PROGRESS_TYPE: plain
            SPRYKER_PLATFORM_IMAGE: spryker/php:8.3
            TRAVIS: 1
            ROBOT_TESTS_ARTIFACTS_BUCKET_REGION: eu-west-1
        steps:
            - name: apt update
              run: sudo apt update

            - uses: actions/setup-python@v4
              with:
                  python-version: '3.9'

            - name: Clone project (suite)
              run: |
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"
                  git clone -b feature/frw-9914/enable-parallel-test-execution --single-branch https://github.com/spryker-shop/suite.git .
            - name: Cache pip packages
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-
            - name: Install robotframework-suite-tests folder
              run: |
                  cd ./data && composer require "spryker/robotframework-suite-tests:dev-feature/frw-9914/master-enable-parallel-test-execution" --dev --no-interaction
                  cp -r vendor ../vendor
            - name: Install packages
              run: |
                  sudo apt-get install apache2-utils
                  sudo apt install awscli -q
                  python3 -m pip install --upgrade pip
            - name: Install docker-compose
              run: |
                  sudo curl -L "https://github.com/docker/compose/releases/download/2.12.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                  sudo chmod +x /usr/local/bin/docker-compose
            # - name: Install Robot tests
            #   run: |
            #       git clone https://github.com/spryker/robotframework-suite-tests.git --single-branch --branch master robotframework-tests
            - name: Install Project
              continue-on-error: false
              run: |
                  git clone https://github.com/spryker/docker-sdk.git ./docker
                  docker/sdk boot -v deploy.ci.acceptance.dynamic-store-off.yml
                  sudo bash -c "echo '127.0.0.1 backend-api.at.spryker.local backend-api.de.spryker.local backend-gateway.at.spryker.local backend-gateway.de.spryker.local backoffice.at.spryker.local backoffice.de.spryker.local date-time-configurator-example.spryker.local glue-backend.at.spryker.local glue-backend.de.spryker.local glue-storefront.at.spryker.local glue-storefront.de.spryker.local glue.at.spryker.local glue.de.spryker.local mp.at.spryker.local mp.de.spryker.local yves.at.spryker.local yves.de.spryker.local' >> /etc/hosts"
                  docker/sdk up -t -v
            - name: Custom commands
              continue-on-error: false
              run: |
                  docker/sdk cli composer dump-autoload -o -a --apcu
                  APPLICATION_STORE=DE docker/sdk console queue:worker:start --stop-when-empty
                  APPLICATION_STORE=AT docker/sdk console queue:worker:start --stop-when-empty
            - name: Run Dynamic Tests Set
              id: run_dynamic_tests
              continue-on-error: true
              run: |
                  docker/sdk exec robot-framework pabot --processes 4 --ordering pabot_suite_ordering -v env:ui_suite -v docker:True -v headless:true -v ignore_console:false -v dms:false -v db_engine:psycopg2 -d results/dynamic_set --exclude skip-due-to-issueORskip-due-to-refactoringORstatic-set -s '*'.tests.parallel_ui.suite .
            - name: Run Static Tests Set
              id: run_static_tests
              continue-on-error: true
              run: |
                  docker/sdk exec robot-framework robot -v env:ui_suite -v docker:True -v headless:true -v ignore_console:false -v dms:false -v db_engine:psycopg2 -d results/static_set --exclude skip-due-to-issueORskip-due-to-refactoring --include static-set -s '*'.tests.parallel_ui.suite .
            - name: Merge Initial Test Results
              id: merge_initial_results
              continue-on-error: true
              run: |
                  docker/sdk exec robot-framework rebot -d results --output output.xml --merge results/dynamic_set/output.xml results/static_set/output.xml
            - name: Upload artifacts
              if: always() && steps.merge_initial_results.outcome != 'success'
              run: |
                  AWS_DEFAULT_REGION=${{env.ROBOT_TESTS_ARTIFACTS_BUCKET_REGION}} AWS_ACCESS_KEY_ID=${{ secrets.ROBOT_TESTS_ARTIFACTS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.ROBOT_TESTS_ARTIFACTS_SECRET }} aws s3 cp .robot/results/log.html s3://${{vars.ROBOT_TESTS_ARTIFACTS_BUCKET}}/debug/split/dms-on/robot-ui/${GITHUB_RUN_ID}/PHP8.2PostgreSQL/log.html