name: Generate random failure
on:
    schedule:
        -   cron: '0 3 * * *'
    workflow_dispatch:
jobs:
  randomly-failing-job:
    runs-on: ubuntu-latest
    steps:
      - name: Generate 0 or 1
        id: generate_number
        run:  echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT

      - name: Pass or fail
        continue-on-error: true
        id: test
        run: |
          if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; then exit 0; else exit 1; fi
      - name: TEST
        if: failure()
        run: |
          if [[ ${{ steps.test.outcome }} == 'success' ]]; then exit 1; else exit 0; fi
      - name: FINAL
        if: always()
        run: |
          if [[ ${{ steps.test.outcome }} == 'success' ]]; then exit 1; else exit 0; fi
